[package]
name = "alder"
version = "0.1.0"
authors = ["Wojciech Polak <frondeus@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
derive_more = "0.15.0"
colored = "1.8.0"

[dev-dependencies]
test-case = "1.0.0-alpha-1"
insta = "0.12.0"
